# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sunny R
email: splttingatms@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sunny's blog where he writes about programming, cycling, 3D printing, 
  whatever is on his mind.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sunnyrodriguez.com" # the base hostname & protocol for your site
github_username:  splttingatms
linkedin_username: sunnyrod
collections:
- projects
permalink: /blog/:year/:month/:day/:title.html
gems: [jekyll-paginate, jekyll-feed]
paginate: 5
paginate_path: "/blog/page:num/"
timezone: US/Pacific